"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 00:24:02.150228
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('camera_location', sa.String(length=50), nullable=True),
    sa.Column('camera_id', sa.String(length=50), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('person_name', sa.String(length=100), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=True),
    sa.Column('channels_sent', sa.String(length=100), nullable=True),
    sa.Column('review_status', sa.String(length=12), server_default='pending', nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_timestamp', 'alerts', ['timestamp', 'alert_type'], unique=False)
    op.create_index('idx_alert_unacknowledged', 'alerts', ['acknowledged', 'dismissed'], unique=False)
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('rtsp_url', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_camera_id'), 'cameras', ['camera_id'], unique=True)
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_table('config_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_key', 'config_entries', ['key'], unique=False)
    op.create_index(op.f('ix_config_entries_id'), 'config_entries', ['id'], unique=False)
    op.create_index(op.f('ix_config_entries_key'), 'config_entries', ['key'], unique=True)
    op.create_table('detection_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('detection_type', sa.String(length=40), nullable=False),
    sa.Column('predicted_label', sa.String(length=40), nullable=True),
    sa.Column('ground_truth', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('labeled_by', sa.String(length=80), nullable=True),
    sa.Column('labeled_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_label_type_truth', 'detection_labels', ['detection_type', 'ground_truth'], unique=False)
    op.create_index(op.f('ix_detection_labels_alert_id'), 'detection_labels', ['alert_id'], unique=False)
    op.create_index(op.f('ix_detection_labels_created_at'), 'detection_labels', ['created_at'], unique=False)
    op.create_index(op.f('ix_detection_labels_detection_type'), 'detection_labels', ['detection_type'], unique=False)
    op.create_index(op.f('ix_detection_labels_evidence_id'), 'detection_labels', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_detection_labels_id'), 'detection_labels', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=True),
    sa.Column('camera_location', sa.String(length=100), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(length=50), nullable=True),
    sa.Column('person_name', sa.String(length=100), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_cam_time', 'events', ['camera_id', 'timestamp'], unique=False)
    op.create_index('idx_event_track', 'events', ['camera_id', 'track_id'], unique=False)
    op.create_index('idx_event_type_time', 'events', ['event_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_alert_id'), 'events', ['alert_id'], unique=False)
    op.create_index(op.f('ix_events_camera_id'), 'events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_table('license_plates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('watchlisted', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plate_number', 'license_plates', ['plate_number'], unique=False)
    op.create_index(op.f('ix_license_plates_id'), 'license_plates', ['id'], unique=False)
    op.create_index(op.f('ix_license_plates_plate_number'), 'license_plates', ['plate_number'], unique=True)
    op.create_table('recording_clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('camera_location', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('alert_type', sa.String(length=40), nullable=True),
    sa.Column('file_path', sa.String(length=400), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=400), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rec_camera_time', 'recording_clips', ['camera_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_recording_clips_camera_id'), 'recording_clips', ['camera_id'], unique=False)
    op.create_index(op.f('ix_recording_clips_id'), 'recording_clips', ['id'], unique=False)
    op.create_index(op.f('ix_recording_clips_started_at'), 'recording_clips', ['started_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vehicle_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('camera_location', sa.String(length=50), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('plate_confidence', sa.String(length=10), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vehicle_timestamp', 'vehicle_detections', ['timestamp', 'camera_location'], unique=False)
    op.create_index(op.f('ix_vehicle_detections_camera_location'), 'vehicle_detections', ['camera_location'], unique=False)
    op.create_index(op.f('ix_vehicle_detections_id'), 'vehicle_detections', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_detections_timestamp'), 'vehicle_detections', ['timestamp'], unique=False)
    op.create_table('known_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('criminal_status', sa.String(length=20), nullable=True),
    sa.Column('threat_level', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_known_category', 'known_persons', ['category'], unique=False)
    op.create_index('idx_known_criminal_status', 'known_persons', ['criminal_status'], unique=False)
    op.create_index('idx_known_person_id', 'known_persons', ['person_id'], unique=False)
    op.create_index(op.f('ix_known_persons_id'), 'known_persons', ['id'], unique=False)
    op.create_index(op.f('ix_known_persons_person_id'), 'known_persons', ['person_id'], unique=True)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('camera_location', sa.String(length=50), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('person_name', sa.String(length=100), nullable=True),
    sa.Column('is_criminal', sa.Boolean(), nullable=True),
    sa.Column('weapon_present', sa.Boolean(), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=True),
    sa.Column('reasons', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('frame_path', sa.String(length=255), nullable=True),
    sa.Column('roi_path', sa.String(length=255), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=True),
    sa.Column('frame_data', sa.LargeBinary(), nullable=True),
    sa.Column('roi_data', sa.LargeBinary(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['known_persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evidence_person_name', 'evidence', ['person_name'], unique=False)
    op.create_index('idx_timestamp_location', 'evidence', ['timestamp', 'camera_location'], unique=False)
    op.create_index('idx_track_time', 'evidence', ['track_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_evidence_camera_location'), 'evidence', ['camera_location'], unique=False)
    op.create_index(op.f('ix_evidence_category'), 'evidence', ['category'], unique=False)
    op.create_index(op.f('ix_evidence_content_sha256'), 'evidence', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_timestamp'), 'evidence', ['timestamp'], unique=False)
    op.create_index(op.f('ix_evidence_track_id'), 'evidence', ['track_id'], unique=False)
    op.create_table('face_encodings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('encoding', sa.LargeBinary(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('encoding_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['known_persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_face_person_id', 'face_encodings', ['person_id'], unique=False)
    op.create_index(op.f('ix_face_encodings_id'), 'face_encodings', ['id'], unique=False)
    op.create_index(op.f('ix_face_encodings_person_id'), 'face_encodings', ['person_id'], unique=False)
    op.create_table('person_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=False),
    sa.Column('image_type', sa.String(length=20), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['known_persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_images_id'), 'person_images', ['id'], unique=False)
    op.create_index(op.f('ix_person_images_person_id'), 'person_images', ['person_id'], unique=False)
    op.create_table('custody_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_custody_evidence_time', 'custody_records', ['evidence_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_custody_records_action'), 'custody_records', ['action'], unique=False)
    op.create_index(op.f('ix_custody_records_created_at'), 'custody_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_custody_records_evidence_id'), 'custody_records', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_custody_records_id'), 'custody_records', ['id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('incident_type', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=True),
    sa.Column('camera_location', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('person_name', sa.String(length=100), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('assigned_name', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incident_camera', 'incidents', ['camera_id', 'created_at'], unique=False)
    op.create_index('idx_incident_status_priority', 'incidents', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_incidents_camera_id'), 'incidents', ['camera_id'], unique=False)
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_incident_type'), 'incidents', ['incident_type'], unique=False)
    op.create_index(op.f('ix_incidents_priority'), 'incidents', ['priority'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_ticket_id'), 'incidents', ['ticket_id'], unique=True)
    op.create_table('incident_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_events_created_at'), 'incident_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_incident_events_id'), 'incident_events', ['id'], unique=False)
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    op.create_table('incident_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=80), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_notes_id'), 'incident_notes', ['id'], unique=False)
    op.create_index(op.f('ix_incident_notes_incident_id'), 'incident_notes', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_notes_incident_id'), table_name='incident_notes')
    op.drop_index(op.f('ix_incident_notes_id'), table_name='incident_notes')
    op.drop_table('incident_notes')
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_id'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_created_at'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_incidents_ticket_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_priority'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_type'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_camera_id'), table_name='incidents')
    op.drop_index('idx_incident_status_priority', table_name='incidents')
    op.drop_index('idx_incident_camera', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_custody_records_id'), table_name='custody_records')
    op.drop_index(op.f('ix_custody_records_evidence_id'), table_name='custody_records')
    op.drop_index(op.f('ix_custody_records_created_at'), table_name='custody_records')
    op.drop_index(op.f('ix_custody_records_action'), table_name='custody_records')
    op.drop_index('idx_custody_evidence_time', table_name='custody_records')
    op.drop_table('custody_records')
    op.drop_index(op.f('ix_person_images_person_id'), table_name='person_images')
    op.drop_index(op.f('ix_person_images_id'), table_name='person_images')
    op.drop_table('person_images')
    op.drop_index(op.f('ix_face_encodings_person_id'), table_name='face_encodings')
    op.drop_index(op.f('ix_face_encodings_id'), table_name='face_encodings')
    op.drop_index('idx_face_person_id', table_name='face_encodings')
    op.drop_table('face_encodings')
    op.drop_index(op.f('ix_evidence_track_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_timestamp'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_content_sha256'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_category'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_camera_location'), table_name='evidence')
    op.drop_index('idx_track_time', table_name='evidence')
    op.drop_index('idx_timestamp_location', table_name='evidence')
    op.drop_index('idx_evidence_person_name', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_known_persons_person_id'), table_name='known_persons')
    op.drop_index(op.f('ix_known_persons_id'), table_name='known_persons')
    op.drop_index('idx_known_person_id', table_name='known_persons')
    op.drop_index('idx_known_criminal_status', table_name='known_persons')
    op.drop_index('idx_known_category', table_name='known_persons')
    op.drop_table('known_persons')
    op.drop_index(op.f('ix_vehicle_detections_timestamp'), table_name='vehicle_detections')
    op.drop_index(op.f('ix_vehicle_detections_id'), table_name='vehicle_detections')
    op.drop_index(op.f('ix_vehicle_detections_camera_location'), table_name='vehicle_detections')
    op.drop_index('idx_vehicle_timestamp', table_name='vehicle_detections')
    op.drop_table('vehicle_detections')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_recording_clips_started_at'), table_name='recording_clips')
    op.drop_index(op.f('ix_recording_clips_id'), table_name='recording_clips')
    op.drop_index(op.f('ix_recording_clips_camera_id'), table_name='recording_clips')
    op.drop_index('idx_rec_camera_time', table_name='recording_clips')
    op.drop_table('recording_clips')
    op.drop_index(op.f('ix_license_plates_plate_number'), table_name='license_plates')
    op.drop_index(op.f('ix_license_plates_id'), table_name='license_plates')
    op.drop_index('idx_plate_number', table_name='license_plates')
    op.drop_table('license_plates')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_camera_id'), table_name='events')
    op.drop_index(op.f('ix_events_alert_id'), table_name='events')
    op.drop_index('idx_event_type_time', table_name='events')
    op.drop_index('idx_event_track', table_name='events')
    op.drop_index('idx_event_cam_time', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_detection_labels_id'), table_name='detection_labels')
    op.drop_index(op.f('ix_detection_labels_evidence_id'), table_name='detection_labels')
    op.drop_index(op.f('ix_detection_labels_detection_type'), table_name='detection_labels')
    op.drop_index(op.f('ix_detection_labels_created_at'), table_name='detection_labels')
    op.drop_index(op.f('ix_detection_labels_alert_id'), table_name='detection_labels')
    op.drop_index('idx_label_type_truth', table_name='detection_labels')
    op.drop_table('detection_labels')
    op.drop_index(op.f('ix_config_entries_key'), table_name='config_entries')
    op.drop_index(op.f('ix_config_entries_id'), table_name='config_entries')
    op.drop_index('idx_config_key', table_name='config_entries')
    op.drop_table('config_entries')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_camera_id'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_index('idx_alert_unacknowledged', table_name='alerts')
    op.drop_index('idx_alert_timestamp', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
